# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  projectPath: '$(system.defaultWorkingDirectory)/src/MunchkinAuth'

steps:
- task: GoTool@0
  inputs:
    version: '1.22.0'
    workingDirectory: '$(projectPath)'
  
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d -v -t'
    workingDirectory: '$(projectPath)'

- task: Go@0
  inputs:
    command: 'build'
    arguments: './cmd/MunchkinAuthServer -o "./out/MunchkinAuthServer"'
    workingDirectory: '$(projectPath)'
