# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Change directory to MunchkinAuth..."
    cd ./src/MunchkinAuth
  
- task: GoTool@0
  inputs:
    version: '1.22.0'
  
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d -v -t'

- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: './cmd/MunchkinAuthServer'
    arguments: '-o "./out/MunchkinAuthServer"'