# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  projectPath: '$(system.defaultWorkingDirectory)/src/MunchkinAuth'

steps:
- script: |
    pwd
    ls -la
    echo $(projectPath)
  displayName: 'Run a one-line script'

- task: GoTool@0
  inputs:
    version: '1.22.0'
    workingDirectory: '$(projectPath)'
  
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d -v -t'
    workingDirectory: '$(projectPath)'

- task: Go@0
  inputs:
    command: 'build'
    arguments: '-o "./out/MunchkinAuthServer" ./cmd/MunchkinAuthServer '
    workingDirectory: '$(projectPath)'
