# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Change directory to MunchkinAuth..."
    cd ./src/MunchkinAuth

    echo "Fetching dependencies..."
    go get -v -t -d ./...

    echo "Building MunchkinAuthServer..."
    go build -v ./cmd/MunchkinAuthServer
  displayName: 'Get dependencies and Build MunchkinAuthServer'

- script: |
    echo "Change directory to MunchkinAuth..."
    cd ./src/MunchkinAuth
    
    echo "Running tests..."
    go test -v ./...
  displayName: 'Run tests'