package constants

const (
	AUTHENTICATORTYPEOPENIDMICROSOFTSUBPATH  = "/openid/microsoft"
	AUTHENTICATORTYPEOPENIDGOOGLESUBPATH     = "/openid/google"
	AUTHENTICATORTYPEOPENIDTENCENTSUBPATH    = "/openid/tencent"
	AUTHENTICATORTYPEUSERNAMEPASSWORDSUBPATH = "/pwd"
)
